export default {
    categories: [
        'Sweater',
        'Dress',
        'Hoodies',
        'T-shirt',
        'Flip-flops',
        'Shorts',
        'Skirt',
        'Jeans',
        'Shoes',
        'Coat',
        'High heels',
        'Cap',
        'Socks',
        'Shirt',
        'Bikini',
        'Bra',
        'Scarf',
        'Hat',
        'Gloves',
        'Jacket',
        'Long coat',
        'Boots',
        'Sunglasses',
        'Tie',
    ],
    colors: [
        "maroon",
        "red",
        "darksalmon",
        "orange",
        "darkkhaki",
        "darkolivegreen",
        "darkgreen",
        "lightgreen",
        "seagreen",
        "teal",
        "darkturquoise",
        "powderblue",
        "dodgerblue",
        "navy",
        "blueviolet",
        "mediumpurple",
        "purple",
        "orchid",
        "lightpink",
        "blanchedalmond",
        "lightyellow",
        "sandybrown",
        "navajowhite",
        "oldlace",
        "lightslategray",
        "ghostwhite",
        "black",
        "lightgray"
    ]
}